version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  registries:
  - github-packages
  schedule:
    interval: weekly
registries:
  github-packages:
    type: maven-repository
    url: https://maven.pkg.github.com/veupathdb/maven-packages
    token: ${{ secrets.PACKAGES_KEY }}
